services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./src:/app/src # Hot reload for development
      - ../data:/app/data # Mount data directory
      - ./logs:/app/logs # Mount logs directory
    command: uv run uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
