services:
  backend:
    image: simple-backend:latest
    container_name: simple-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    volumes:
      - ../../data:/app/data # Mount data directory from root
      - ../logs:/app/logs # Mount logs directory
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
