"""Create all models with proper Base

Revision ID: b5171378a784
Revises: 
Create Date: 2025-06-24 13:21:56.207432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5171378a784'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('url_bookmarks',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('userId', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_url_bookmarks_categories', 'url_bookmarks', ['categories'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('userId', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_userId'), 'user', ['userId'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('userId', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_userId'), 'feedback', ['userId'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('postId', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=200), nullable=True),
    sa.Column('types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('generationText', sa.Text(), nullable=True),
    sa.Column('generationUrl', sa.String(length=1000), nullable=True),
    sa.Column('isPublic', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('userId', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('postId')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('userId', sa.String(length=255), nullable=False),
    sa.Column('postId', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['posts.postId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'postId', name='uq_user_post_bookmark')
    )
    op.create_table('likes',
    sa.Column('userId', sa.String(length=255), nullable=False),
    sa.Column('postId', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['posts.postId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId', 'postId'),
    sa.UniqueConstraint('userId', 'postId', name='uq_user_post_like')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('bookmarks')
    op.drop_table('posts')
    op.drop_index(op.f('ix_feedback_userId'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_user_userId'), table_name='user')
    op.drop_table('user')
    op.drop_index('idx_url_bookmarks_categories', table_name='url_bookmarks')
    op.drop_table('url_bookmarks')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ### 